# Introduction to Python

## 1. Python Basics

### Variable Assignment
Instructions:
<ul>
<li>Create a variable savings with the value 100.</li>
<li>Check out this variable by typing <code>print(savings)</code> in the script.</li>
</ul>

In [1]:
# Create a variable savings
savings = 100

# Print out savings
print(savings)

100


### Calculations with variables
Instructions:
<ul>
<li>Create a variable growth_multiplier, equal to 1.1.</li>
<li>Create a variable, result, equal to the amount of money you saved after 7 years.</li>
<li>Print out the value of result..</li>
</ul>

In [2]:
# Create a variable savings
savings = 100

# Create a variable growth_multiplier
growth_multiplier = 1.1

# Calculate result
result = savings * growth_multiplier ** 7

# Print out result
print(result)

194.87171000000012


### Other variable types
Instructions:
<ul>
<li>Create a new string, desc, with the value "compound interest".</li>
<li>Create a new boolean, profitable, with the value True.</li>
</ul>

In [3]:
# Create a variable desc
desc = "compound interest"

# Create a variable profitable
profitable = True

### Operations with other types
Instructions:
<ul>
<li>Calculate the product of savings and growth_multiplier. Store the result in year1.</li>
<li>What do you think the resulting type will be? Find out by printing out the type of year1.</li>
<li>Calculate the sum of desc and desc and store the result in a new variable doubledesc.</li>
<li>Print out doubledesc. Did you expect this?</li>
</ul>

In [4]:
savings = 100
growth_multiplier = 1.1
desc = "compound interest"

# Assign product of savings and growth_multiplier to year1
year1 = savings * growth_multiplier

# Print the type of year1
print(type(year1))

# Assign sum of desc and desc to doubledesc
doubledesc = desc + desc

# Print out doubledesc
print(doubledesc)

<class 'float'>
compound interestcompound interest


### Type conversion
Instructions:
<ul>
<li>Hit Run Code to run the code. Try to understand the error message.</li>
<li>Fix the code such that the printout runs without errors; use the function str() to convert the variables to strings.</li>
<li>Convert the variable pi_string to a float and store this float as a new variable, pi_float.</li>
</ul>

In [5]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

I started with $100 and now have $194.87171000000012. Awesome!


## 2. Python Lists

### Create a list
Instructions:
<ul>
<li>Create a list, areas, that contains the area of the hallway (<i>hall</i>), kitchen (<i>kit</i>), living room (<i>liv</i>), bedroom (<i>bed</i>) and bathroom (<i>bath</i>), in this order. Use the predefined variables.</li>
<li>Print <i>areas</i> with the <code>print()</code> function.</li>
</ul>

In [6]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


### Create list with different types
Instructions:
<ul>
<li>Finish the code that creates the <i>areas</i> list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings <i>"hallway"</i>, <i>"kitchen"</i> and <i>"bedroom"</i> at the appropriate locations.</li>
<li>Print <i>areas</i> again; is the printout more informative this time?</li>
</ul>

In [7]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


### List of lists
Instructions:
<ul>
<li>Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!</li>
<li>Print out <i>house</i>; does this way of structuring your data make more sense?</li>
<li>Print out the type of <i>house</i>. Are you still dealing with a list?</li>
</ul>

In [8]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


### Subset and calculate
Instructions:
<ul>
<li>Using a combination of list subsetting and variable assignment, create a new variable, <i>eat_sleep_area</i>, that contains the sum of the area of the kitchen and the area of the bedroom.</li>
<li>Print the new variable <i>eat_sleep_area</i>.</li>
</ul>

In [9]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]

# Print the variable eat_sleep_area
print(eat_sleep_area)


28.75


### Slicing and dicing
Instructions:
<ul>
<li>Use slicing to create a list, <i>downstairs</i>, that contains the first 6 elements of <i>areas</i>.</li>
<li>Do a similar thing to create a new variable, <i>upstairs</i>, that contains the last 4 elements of <i>areas</i>.</li>
<li>Print both <i>downstairs</i> and <i>upstairs</i> using print().</li>
</ul>

In [10]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[-4:]

# Print out downstairs and upstairs
print(downstairs, upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0] ['bedroom', 10.75, 'bathroom', 9.5]


### Slicing and dicing (2)
Instructions:
<ul>
<li>Create <i>downstairs</i> again, as the first 6 elements of <i>areas</i>. This time, simplify the slicing by omitting the <i>begin</i> index.</li>
<li>Create <i>upstairs</i> again, as the last <i>4</i> elements of <i>areas</i>. This time, simplify the slicing by omitting the <i>end</i> index.</li>
</ul>

In [11]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs
downstairs = areas[:6]

# Alternative slicing to create upstairs
upstairs = areas[-4:]

### Replace list elements
Instructions:
<ul>
<li>Update the area of the bathroom area to be 10.50 square meters instead of 9.50.</li>
<li>Make the <i>areas</i> list more trendy! Change <i>"living room"</i> to <i>"chill zone"</i>.</li>
</ul>

In [12]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

### Extend a list
Instructions:
<ul>
<li>Use the + operator to paste the list <i>["poolhouse", 24.5]</i> to the end of the <i>areas<li> list. Store the resulting list as <i>areas_1</i>.</li>
<li>Further extend <i>areas_1</i> by adding data on your garage. Add the string <i>"garage"</i> and float <i>15.45</i>. Name the resulting list <i>areas_2</i>.</li>
</ul>

In [13]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

### Inner workings of lists
Instructions:
<ul>
<li>Change the second command, that creates the variable areas_copy, such that areas_copy is an explicit copy of areas. After your edit, changes made to areas_copy shouldn't affect areas. Submit the answer to check this.</li>
</ul>

In [14]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


### Subset and conquer
Instructions:
<ul>
<li>Print out the second element from the <i>areas</i> list (it has the value <i>11.25</i>).</li>
<li>Subset and print out the last element of <i>areas</i>, being <i>9.50</i>. Using a negative index makes sense here!</li>
<li>Select the number representing the area of the living room (<i>20.0</i>) and print it out.</li>
</ul>

In [15]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


## 3. Functions and Packages

### Familiar functions
Instructions:
<ul>
<li>Use print() in combination with type() to print out the type of var1.</li>
<li>Use len() to get the length of the list var1. Wrap it in a print() call to directly print it out.</li>
<li>Use int() to convert var2 to an integer. Store the output as out2.</li>
</ul>

In [16]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


### Multiple arguments
Instructions:
<ul>
<li>Use + to merge the contents of first and second into a new list: full.</li>
<li>Call sorted() on full and specify the reverse argument to be True. Save the sorted list as full_sorted.</li>
<li>Finish off by printing out full_sorted.</li>
</ul>

In [17]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


### String Methods
Instructions:
<ul>
<li>Use the upper() method on place and store the result in place_up. Use the syntax for calling methods that you learned in the previous video.</li>
<li>Print out place and place_up. Did both change?</li>
<li>Print out the number of o's on the variable place by calling count() on place and passing the letter 'o' as an input to the method. We're talking about the variable place, not the word "place"!</li>
</ul>

In [18]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place, place_up)

# Print out the number of o's in place
print(place.count('o'))

poolhouse POOLHOUSE
3


### List Methods
Instructions:
<ul>
<li>Use the index() method to get the index of the element in areas that is equal to 20.0. Print out this index.</li>
<li>Call count() on areas to find out how many times 9.50 appears in the list. Again, simply print out this number.</li>
</ul>

In [19]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))


2
1


### List Methods (2)
Instructions:
<ul>
<li>Use append() twice to add the size of the poolhouse and the garage again: 24.5 and 15.45, respectively. Make sure to add them in this order.</li>
<li>Print out areas</li>
<li>Use the reverse() method to reverse the order of the elements in areas.</li>
<li>Print out areas once more.</li>
</ul>

In [20]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


### Import package
Instructions:
<ul>
<li>Import the math package. Now you can access the constant pi with math.pi.</li>
<li>Calculate the circumference of the circle and store it in C.</li>
<li>Calculate the area of the circle and store it in A</li>
</ul>

In [21]:
# Definition of radius
r = 0.43

# Import the math package
import math as mt

# Calculate C
C = 2*mt.pi*r

# Calculate A
A = mt.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


### Selective import
Instructions:
<ul>
<li>Perform a selective import from the math package where you only import the radians function.</li>
<li>Calculate the distance travelled by the Moon over 12 degrees of its orbit. Assign the result to dist. You can calculate this as r * phi, where r is the radius and phi is the angle in radians. To convert an angle in degrees to an angle in radians, use the radians() function, which you just imported.</li>
<li>Print out dist.</li>
</ul>

In [22]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


## 4. NumPy

### Your First NumPy Array
Instructions:
<ul>
<li>Import the numpy package as np, so that you can refer to numpy with np.</li>
<li>Use np.array() to create a numpy array from baseball. Name this array np_baseball.</li>
<li>Print out the type of np_baseball to check that you got it right.</li>
</ul>

In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


### Baseball players' height
Instructions:
<ul>
<li>Create a numpy array from height_in. Name this new array np_height_in.</li>
<li>Print np_height_in.</li>
<li>Multiply np_height_in with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array, np_height_m.</li>
<li>Print out np_height_m and check if the output makes sense.</li>
</ul>

In [24]:
# height_in is available as a regular list

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

NameError: name 'height_in' is not defined

### Baseball player's BMI
Instructions:
<ul>
<li>Create a numpy array from the weight_lb list with the correct units. Multiply by 0.453592 to go from pounds to kilograms. Store the resulting numpy array as np_weight_kg.</li>
<li>Use np_height_m and np_weight_kg to calculate the BMI of each player. Use the following equation: BMI = weight(kg) / height(m²)</li>
<li>Save the resulting numpy array as bmi.</li>
<li>Print out bmi.</li>
</ul>

In [3]:
# height_in and weight_lb are available as regular lists

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)

NameError: name 'height_in' is not defined

### Lightweight baseball players
Instructions:
<ul>
<li>Create a boolean numpy array: the element of the array should be True if the corresponding baseball player's BMI is below 21. You can use the < operator for this. Name the array light.</li>
<li>Print the array light.</li>
<li>Print out a numpy array with the BMIs of all baseball players whose BMI is below 21. Use light inside square brackets to do a selection on the bmi array.</li>
</ul>

In [4]:
# height_in and weight_lb are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = np.array(bmi < 21)

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

NameError: name 'height_in' is not defined

### Subsetting NumPy Arrays
Instructions:
<ul>
<li>Subset np_weight_lb by printing out the element at index 50.</li>
<li>Print out a sub-array of np_height_in that contains the elements at index 100 up to and including index 110.</li>
</ul>

In [5]:
# height_in and weight_lb are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[100:111])

NameError: name 'weight_lb' is not defined

### Your First 2D NumPy Array
Instructions:
<ul>
<li>Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.</li>
<li>Print out the type of np_baseball.</li>
<li>Print out the shape attribute of np_baseball. Use np_baseball.shape.</li>
</ul>

In [6]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


### Baseball data in 2D form
Instructions:
<ul>
<li>Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.</li>
<li>Print out the shape attribute of np_baseball.</li>
</ul>

In [7]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


### Subsetting 2D NumPy Arrays
Instructions:
<ul>
<li>Print out the 50th row of np_baseball.</li>
<li>Make a new variable, np_weight_lb, containing the entire second column of np_baseball.</li>
<li>Select the height (first column) of the 124th baseball player in np_baseball and print it out.</li>
</ul>

In [8]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[:50, :])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np.array(np_baseball[:, 1])

# Print out height of 124th player
print(np_baseball[123, 0])

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


IndexError: index 123 is out of bounds for axis 0 with size 4

### 2D Arithmetic
Instructions:
<ul>
<li>You managed to get hold of the changes in height, weight and age of all baseball players. It is available as a 2D numpy array, updated. Add np_baseball and updated and print out the result.</li>
<li>You want to convert the units of height and weight to metric (meters and kilograms, respectively). As a first step, create a numpy array with three values: 0.0254, 0.453592 and 1. Name this array conversion.</li>
<li>Multiply np_baseball with conversion and print out the result.</li>
</ul>

In [9]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

NameError: name 'updated' is not defined

### Average versus median
Instructions:
<ul>
<li>Create numpy array np_height_in that is equal to first column of np_baseball.</li>
<li>Print out the mean of np_height_in.</li>
<li>Print out the median of np_height_in.</li>
</ul>

In [10]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np.array(np_baseball[:,0])

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

198.25
199.0


### Explore the baseball data
Instructions:
<ul>
<li>The code to print out the mean height is already included. Complete the code for the median height. Replace None with the correct code.</li>
<li>Use np.std() on the first column of np_baseball to calculate stddev. Replace None with the correct code.</li>
<li>Do big players tend to be heavier? Use np.corrcoef() to store the correlation between the first and second column of np_baseball in corr. Replace None with the correct code.</li>
</ul>

In [11]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]


### Blend it all together
Instructions:
<ul>
<li>Convert heights and positions, which are regular lists, to numpy arrays. Call them np_heights and np_positions.</li>
<li>Extract all the heights of the goalkeepers. You can use a little trick here: use np_positions == 'GK' as an index for np_heights. Assign the result to gk_heights.</li>
<li>Extract all the heights of all the other players. This time use np_positions != 'GK' as an index for np_heights. Assign the result to other_heights.</li>
<li>Print out the median height of the goalkeepers using np.median(). Replace None with the correct code.</li>
<li>Do the same for the other players. Print out their median height. Replace None with the correct code.</li>
</ul>

In [12]:
# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_heights = np.array(heights)
np_positions = np.array(positions)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

NameError: name 'heights' is not defined